
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      
      - run:
          name: make pack
          command: make pack

      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST  >> ~/.ssh/known_hosts
      - run: sudo apt-get update && sudo apt-get install sshpass 
      - run:
          name: scp upload package
          command:  sshpass -p $SSH_PASSWORD  scp -P $SSH_PORT  ansible/files/simpletodoapp-1.0.1.tgz root@$SSH_HOST:~
      - run: 
          name: ssh run simple todo app
          command: sshpass -p $SSH_PASSWORD  ssh -p $SSH_PORT  root@$SSH_HOST "ls"

workflows:
  deploy: 
    jobs:
      - deploy