
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      
      - run:
          name: make pack
          command: make pack

      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST  >> ~/.ssh/known_hosts
      - run: sudo apt-get update && sudo apt-get -f install sshpass 
      - run:
          name: scp upload package
          command:  sshpass -p $SSH_PASSWORD  scp -P $SSH_PORT  README.txt root@$SSH_HOST:~

workflows:
  deploy: 
    jobs:
      - deploy
