
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      
      - run:
          name: make pack
          command: make pack
      - run:
          name: scp upload package
          command:  scp -P $SSH_PORT ansible/files/simpletodoapp-1.0.1.tgz root:$SSH_PASSWORD@$SSH_HOST:~

workflows:
  deploy: 
    jobs:
      - deploy
