
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      
      - run:
          name: make pack
          command: make pack

workflows:
  deploy: 
    jobs:
      - deploy
