
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      
      - run:
          name: make pack
          command: make pack

      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST  >> ~/.ssh/known_hosts
      - run:
          name: scp upload package
          command:  scp -P $SSH_PORT -p $SSH_PASSWORD ansible/files/simpletodoapp-1.0.1.tgz root@$SSH_HOST:~

workflows:
  deploy: 
    jobs:
      - deploy
